/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_SurfaceTexture */

#ifndef _Included_android_graphics_SurfaceTexture
#define _Included_android_graphics_SurfaceTexture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    nativeCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_SurfaceTexture_nativeCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    nativeAttach
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_SurfaceTexture_nativeAttach
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    nativeDetach
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_SurfaceTexture_nativeDetach
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    nativeUpdate
 * Signature: (JI[BII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_SurfaceTexture_nativeUpdate
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
