/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Typeface */

#ifndef _Included_android_graphics_Typeface
#define _Included_android_graphics_Typeface
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Typeface_NORMAL
#define android_graphics_Typeface_NORMAL 0L
#undef android_graphics_Typeface_BOLD
#define android_graphics_Typeface_BOLD 1L
#undef android_graphics_Typeface_ITALIC
#define android_graphics_Typeface_ITALIC 2L
#undef android_graphics_Typeface_BOLD_ITALIC
#define android_graphics_Typeface_BOLD_ITALIC 3L
/*
 * Class:     android_graphics_Typeface
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Typeface_nativeCreate
  (JNIEnv *, jclass, jstring, jint, jboolean);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeLoad
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Typeface_nativeLoad
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeCopy
 * Signature: (JIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Typeface_nativeCopy
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeStyle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Typeface_nativeStyle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Typeface_nativeRelease
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
