/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_Surface */

#ifndef _Included_android_view_Surface
#define _Included_android_view_Surface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_Surface
 * Method:    nativeResetCanvas
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_view_Surface_nativeResetCanvas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_view_Surface
 * Method:    nativePostCanvas
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_view_Surface_nativePostCanvas
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
