/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_webkit_CookieManager */

#ifndef _Included_android_webkit_CookieManager
#define _Included_android_webkit_CookieManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_webkit_CookieManager
 * Method:    getCookie
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_webkit_CookieManager_getCookie
  (JNIEnv *, jobject, jstring);

/*
 * Class:     android_webkit_CookieManager
 * Method:    hasCookies
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_webkit_CookieManager_hasCookies
  (JNIEnv *, jobject);

/*
 * Class:     android_webkit_CookieManager
 * Method:    nativeSet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_webkit_CookieManager_nativeSet
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     android_webkit_CookieManager
 * Method:    nativeRemove
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_webkit_CookieManager_nativeRemove
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_webkit_CookieManager
 * Method:    nativeFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_webkit_CookieManager_nativeFlush
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
