/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_hardware_HardwareBuffer */

#ifndef _Included_android_hardware_HardwareBuffer
#define _Included_android_hardware_HardwareBuffer
#ifdef __cplusplus
extern "C" {
#endif
#undef android_hardware_HardwareBuffer_BLOB
#define android_hardware_HardwareBuffer_BLOB 33L
#undef android_hardware_HardwareBuffer_USAGE_CPU_READ_RARELY
#define android_hardware_HardwareBuffer_USAGE_CPU_READ_RARELY 2LL
#undef android_hardware_HardwareBuffer_USAGE_CPU_READ_OFTEN
#define android_hardware_HardwareBuffer_USAGE_CPU_READ_OFTEN 3LL
#undef android_hardware_HardwareBuffer_USAGE_CPU_WRITE_RARELY
#define android_hardware_HardwareBuffer_USAGE_CPU_WRITE_RARELY 32LL
#undef android_hardware_HardwareBuffer_USAGE_CPU_WRITE_OFTEN
#define android_hardware_HardwareBuffer_USAGE_CPU_WRITE_OFTEN 48LL
/*
 * Class:     android_hardware_HardwareBuffer
 * Method:    create
 * Signature: (IIIIJ)Landroid/hardware/HardwareBuffer;
 */
JNIEXPORT jobject JNICALL Java_android_hardware_HardwareBuffer_create
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong);

/*
 * Class:     android_hardware_HardwareBuffer
 * Method:    nativeRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_HardwareBuffer_nativeRelease
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
